'use client'
import { ThirdwebProvider, metamaskWallet, walletConnect, coinbaseWallet, trustWallet} from '@thirdweb-dev/react'
import {BinanceTestnet} from '@thirdweb-dev/chains'

import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'ENSC Energy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThirdwebProvider activeChain={BinanceTestnet} clientId='5857f3fb0d9aaa3a459e91e6cbae5c6f'  supportedChains = {[BinanceTestnet]} supportedWallets={[
      metamaskWallet({recommended: true}),
     walletConnect(),
     coinbaseWallet(),
     trustWallet()
    ]}  >
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ThirdwebProvider>
  )
}
